### ISSUE TITLE
Remove requirement to pass icons in styles

### ISSUE THREAD

**Issue by TylerAHolden** [iding-ir/typescript-windows#2]
If you pass styles without icons it crashes from a type error but after reviewing the code, it seems that the styles are not spread onto the default props so it completely overrides them. And then the icons dont seem to be exported so you cant get them from the package.

This seems to be the start of a pretty neat package would you want some help?

**Comment by iding-ir** [comment]
Yes of course.

**Comment by TylerAHolden** [comment]
I'm on a really tight deadline so I'm going to clone the repo, make my changes and then at the end ill submit a PR so you can see everything I've done and you can decide if you want to move forward with my changes... I just don't have time to contribute slowly on this repo and I don't want to rush any changes here without your approval. I really like the library so far tho, I haven't found anything like it to compare it with.
